sample/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from tag import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tag.urls', namespace='tag')),
    url(r'^user-tags/', views.UserInfoApi.as_view()),
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tag/urls.py
from django.conf.urls import url

from . import views

# app_name = 'tag'
urlpatterns = [
    url(r'^$', views.log_in, name='log_in'),
    url(r'^form/', views.form, name='form'),
    url(r'^logout/$', views.log_out, name='log_out'),
    url(r'^tag-generator/', views.tag_generator, name='tag_generator'),
    url(r'^image/', views.image, name='image'),
    url(r'^all-tags/', views.all_tags, name='all_tags'),
    url(r'^seen-tags/', views.seen_tags, name='seen_tags'),
    url(r'^mail-seen-tags/', views.mail_seen_tags, name='mail_seen_tags'),
    url(r'^instructions/$', views.instructions, name='instructions'),

]

tag/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib.postgres.fields import JSONField
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User1(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    picture_url = models.CharField(max_length=1000,
                                   default="https://jtkwriting.files.wordpress.com/2015/01/7rf-d-60.jpg")
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)


class UserInfo(models.Model):
    user = models.ForeignKey(User1, related_name='user_info')
    user_tag = models.CharField(max_length=50)
    generated_tag = models.CharField(max_length=100)
    user_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user_tag


class ClientInfo(models.Model):
    user_info = models.ForeignKey(UserInfo, related_name='client_info')
    client_time = models.DateTimeField(default=timezone.now)
    client_meta = JSONField(default={})
    times_seen = models.IntegerField(default=0)
    client_agent = models.CharField(max_length=200, default="DZ / jaz / Zome 62.0.3202")

    def __str__(self):
        return self.user_info.user_tag

tag/views.py
# import simplejson as json
import os
import uuid

from PIL import Image
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.decorators.cache import cache_page
from google.auth.transport import requests
from google.oauth2 import id_token
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import User1, UserInfo, ClientInfo
from .serializers import UserInfoSerializer

# import string

CLIENT_ID = os.environ["CLIENT_ID"]

BASE_TAG_URL = "https://trackdown.herokuapp.com/image?image_tag="


# tag_link = ""
# user_tag = ""


class UserInfoApi(APIView):
    @staticmethod
    def get(request):
        email = request.GET.get('email')
        # user = authenticate(email=email, password="password")
        print(email)
        try:
            user_info = UserInfo.objects.filter(user=request.user)
        except Exception:
            raise Http404("does")
        serializer = UserInfoSerializer(user_info, many=True)
        return Response(serializer.data)


def log_in(request):
    # global user_tag
    # global tag_link
    # tag_link = ""
    # user_tag = ""
    # times = os.environ['tick']
    # print (times)
    # print request.get_full_path()
    token = request.GET.get('token')
    if (request.method == "GET") & (token is not None):
        # token = request.GET.get('token')
        # print(token)
        try:
            idinfo = id_token.verify_oauth2_token(token, requests.Request(), CLIENT_ID)
            # print("iss")
            # print(idinfo['iss'])
            # Or, if multiple clients access the backend server:
            # idinfo = id_token.verify_oauth2_token(token, requests.Request())
            # if idinfo['aud'] not in [CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]:
            #     raise ValueError('Could not verify audience.')

            if idinfo['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
                raise ValueError('Wrong issuer.')

            # If auth request is from a G Suite domain:
            # if idinfo['hd'] != GSUITE_DOMAIN_NAME:
            #     raise ValueError('Wrong hosted domain.')

            # ID token is valid. Get the user's Google Account ID from the decoded token.
            userid = idinfo['sub']

        except ValueError:
            print ("error")
            return redirect('tag:log_in')
            # Invalid token

        # response = requests.get('https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=' + token)
        # data = json.loads(response.content)

        print(idinfo["email"])
        user = authenticate(email=idinfo["email"], password="cameocomuf")
        if user is not None:
            user.first_name = idinfo["given_name"]
            user.last_name = idinfo["family_name"]
            user.picture_url = idinfo["picture"]
            user.save()
            login(request, user)
        else:
            user = User1.objects.create_user(idinfo["email"], "cameocomuf")
            user.first_name = idinfo["given_name"]
            user.last_name = idinfo["family_name"]
            user.picture_url = idinfo["picture"]
            user.save()
            user = authenticate(email=idinfo["email"], password="cameocomuf")
            login(request, user)
        return redirect('tag:tag_generator')

    if not request.user.is_authenticated():
        return render(request, 'login.html')
    # user = request.user
    # context = {'name': user.first_name, 'picture': user.picture_url}
    request.session['user_tag'] = ""
    request.session['tag_link'] = ""
    return redirect('tag:tag_generator')


def log_out(request):
    # print request.get_full_path()
    # global user_tag
    # global tag_link
    # tag_link = ""
    # user_tag = ""
    logout(request)
    return redirect('tag:log_in')


@login_required
def form(request):
    # global user_tag
    user_tag = request.GET.get('tagname')
    print(user_tag)
    if (request.method == "GET") & (user_tag is not None):
        generated_tag = str(uuid.uuid4())
        # global tag_link
        # tag_link = generated_tag
        request.session['user_tag'] = user_tag
        request.session['tag_link'] = generated_tag
        now = timezone.now().strftime('%H:%M:%S')
        print (now)
        userinfo = UserInfo()
        userinfo.user = request.user
        userinfo.user_tag = user_tag.strip()
        userinfo.generated_tag = generated_tag
        userinfo.time = timezone.now()
        userinfo.save()
    return redirect('tag:tag_generator')


@login_required
def tag_generator(request):
    now = timezone.now().strftime("Time:  %H:%M:%S, Day:  %d:%b:%y")
    print (now)
    user = request.user
    print(user.first_name)
    context = {'name': user.first_name, 'picture': user.picture_url, 'email_id': user.email, }
    # userIn = UserInfo.objects.filter(user=request.user)
    # if len(userIn) > 0:
    #     tag = userIn[len(userIn) - 1]
    #     link = BASE_TAG_URL + tag.generated_tag
    # else:
    #     link = ""
    user_tag = request.session.get('user_tag')
    tag_link = request.session.get('tag_link')
    if (tag_link != "") & (tag_link is not None):
        link = BASE_TAG_URL + tag_link
    else:
        link = ""
    context.update({'generated_tag': link, 'prev_tag': user_tag})

    return render(request, 'tag.html', context)


def trim(agent):
    agent = agent.split('/')
    last = agent[2].strip()
    last = last.split(' ')[0]
    agent[2] = last
    agent = "/".join(agent)
    print agent
    return agent


def useful_meta(meta):
    list_keys = ['LOGNAME', 'USER', 'HTTP_USER_AGENT', 'HTTP_HOST', 'SERVER_NAME', 'REMOTE_HOST', 'REMOTE_USER',
                 'SERVER_PORT', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']
    data = {}
    for key in list_keys:
        try:
            data.update({key: meta[key]})
        except Exception:
            pass
    print(data)
    return data


@cache_page(0)
def image(request):
    print(request.user_agent)
    tag = request.GET.get('image_tag')
    user_info = UserInfo.objects.filter(generated_tag=tag)
    print request.META
    print(user_info)
    if len(user_info) > 0:
        current_user_agent = trim(request.user_agent.__str__())
        current_IP = request.META['HTTP_X_FORWARDED_FOR']
        client_info = user_info[0].client_info.filter(client_agent=current_user_agent).filter(
            client_meta__REMOTE_ADDR=current_IP)

        if len(client_info) == 0:
            client = ClientInfo()
            client.user_info = user_info[0]
            client.client_agent = trim(request.user_agent.__str__())
            client.times_seen = 1
        else:
            client = client_info[0]
            client.times_seen += 1

        client.time = timezone.now()
        client.client_meta = useful_meta(request.META)
        client.save()
        img = Image.new("RGB", (1, 1), "#ffffff")
        # serialize to HTTP response
        response = HttpResponse(content_type="image/png")
        img.save(response, "PNG")
        return response
    raise Http404


@login_required
def all_tags(request):
    user = request.user
    user_info = UserInfo.objects.filter(user=user)
    context = {'name': user.first_name, 'picture': user.picture_url, 'email_id': user.email, }
    context.update({'user_info': user_info, 'BASE_TAG_URL': BASE_TAG_URL})
    return render(request, "allTags.html", context)


@login_required
def seen_tags(request):
    user = request.user
    clients = ClientInfo.objects.filter(user_info__user=user)
    newlist = sorted(clients, key=lambda k: k.client_time, reverse=True)
    context = {'name': user.first_name, 'picture': user.picture_url, 'email_id': user.email, }
    context.update({'client_info': newlist, 'BASE_TAG_URL': BASE_TAG_URL})
    return render(request, "seenTags.html", context)


def check_for_mail_proxy(agent):
    agent = agent.split('/')
    if agent[2] == 'GmailImageProxy':
        return True
    return False


@login_required
def mail_seen_tags(request):
    user = request.user
    # clients = ClientInfo.objects.filter(user_info__user=user)
    user_info = UserInfo.objects.filter(user=user)
    clients = []
    for info in user_info:
        times = 0
        client_info = ClientInfo.objects.filter(user_info=info)
        for client in client_info:
            if check_for_mail_proxy(client.client_agent):
                times += client.times_seen
            if times > 2:
                clients.append(client)
                break
    context = {'name': user.first_name, 'picture': user.picture_url, 'email_id': user.email, }
    context.update({'client_info': clients, 'BASE_TAG_URL': BASE_TAG_URL})
    return render(request, "gmailtracked.html", context)


@login_required
def instructions(request):
    user = request.user
    context = {'name': user.first_name, 'picture': user.picture_url, 'email_id': user.email, }
    return render(request, "instructions.html", context)

templates/allTags.html
{% extends 'index.html' %}

{% block title %}
    All Tags
{% endblock %}
{% block header %}
    All tags
{% endblock %}


{% block script %}
    {% load staticfiles %}
    <meta charset="UTF-8" name="google-signin-client_id"
          content="642931691711-njc9uv4lt3lhnnqeh6bq26crdacqpt29.apps.googleusercontent.com">
    <link rel="stylesheet" type="text/css" href="{% static 'tag/css/allTags.css' %}"/>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
{% endblock %}



{% block body %}

    <div id="parent">
        <div id="allTags_table">
            <table class="highlight">
                <thead>
                <tr>
                    <!-- class "mdl-data-table__cell--non-numeric", align values to left -->
                    <th>Tag</th>
                    <th>Generated Address</th>
                    <th>Time</th>
                </tr>
                </thead>
                <tbody>

                <!-- Row 1 -->
                {% for info in user_info %}
                    <tr>
                        <!-- class "mdl-data-table__cell--non-numeric", align values to left -->
                        <td>{{ info.user_tag }}</td>
                        <td>{{ BASE_TAG_URL }}{{ info.generated_tag }}</td>
                        <td>{{ info.user_time }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>

{% endblock %}

templates/gmailtracked.html
{% extends 'index.html' %}

{% block title %}
   tracked mails
{% endblock %}
{% block header %}
    Tracked Mails
{% endblock %}

{% block script %}
    {% load staticfiles %}
        <meta charset="UTF-8" name="google-signin-client_id"
              content="642931691711-njc9uv4lt3lhnnqeh6bq26crdacqpt29.apps.googleusercontent.com">
        <link rel="stylesheet" type="text/css" href="{% static 'tag/css/gmailtracked.css' %}"/>
        <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
{% endblock %}
{% block body %}


    <div id="parent">
        <div id="mail_Tags_table">
            <table class="highlight">
                <thead>
                <tr>
                    <!-- class "mdl-data-table__cell--non-numeric", align values to left -->
                    <th>Tag</th>
                    <th>Generated Address</th>
                    <th>Time</th>
                </tr>
                </thead>
                <tbody>

                <!-- Row 1 -->
                {% for info in client_info %}
                    <tr>
                        <!-- class "mdl-data-table__cell--non-numeric", align values to left -->
                        <td>{{ info.user_info.user_tag }}</td>
                        <td>{{ BASE_TAG_URL }}{{ info.user_info.generated_tag }}</td>
                        <td>{{ info.client_time }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}index{% endblock %}</title>

    {% load staticfiles %}

    <link rel="shortcut icon" type="image/svg" href="{% static 'tag/favicon.ico' %}"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/js/materialize.min.js"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'tag/css/index.css' %}"/>


    <script src="{% static 'tag/js/index.js' %}"></script>
    {% block script %}
    {% endblock %}

</head>
<body>
<header>
    <div class="navbar">
        <nav>
            <div class="nav-wrapper blue darken-4" >

                <a href="{% url 'tag:tag_generator' %}" id="logo" class="brand-logo">{% block header %}
                    logo{% endblock %}</a>
                <a href="#" data-target="slide-out" class="sidenav-trigger "><i class="material-icons">menu</i></a>
                <div id="help_option">
                    <ul class="right ">

                        <li><a id="image_help" href="{% url 'tag:instructions' %}"><img src="{% static 'tag/images/help_36px.svg' %}"/></a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>

    </div>

    <ul id="slide-out" class="sidenav sidenav-fixed">

        <li>
            <div class="user-view">
                <div class="background">
                    <img src="{% static 'tag/images/background_website.jpg' %}">
                </div>
                <a href="#"><img class="circle" src="{{ picture }}"></a>
                <a href="#"><span class="white-text name">{{ name }}</span></a>
                <a href="#"><span class="white-text email">{{ email_id }}</span></a>
            </div>
        </li>

        <li><a class="active" href="{% url 'tag:tag_generator' %}">Make a Tag</a></li>
        <li><a class="waves-effect" href="{% url 'tag:mail_seen_tags' %}">Tracked Gmails</a></li>
        <li><a class="waves-effect" href="{% url 'tag:seen_tags' %}"> All Tracked Tags</a></li>

        <li><a class="waves-effect" href="{% url 'tag:all_tags' %}">All Tags</a></li>

        <li>
            <div class="divider"></div>
        </li>

        <li><a class="waves-effect" href="{% url 'tag:log_out' %}" onclick="signOut();">logout</a></li>
    </ul>


</header>

<main>
    <div>

        {% block body %}

        {% endblock %}
    </div>
</main>


</body>
</html>

templates/instructions.html
{% extends 'index.html' %}

{% block title %}
    instructions
{% endblock %}
{% block header %}
    Instructions
{% endblock %}


{% block script %}
     {% load staticfiles %}
        <meta charset="UTF-8" name="google-signin-client_id"
              content="642931691711-njc9uv4lt3lhnnqeh6bq26crdacqpt29.apps.googleusercontent.com">
        <link rel="stylesheet" type="text/css" href="{% static 'tag/css/instructions.css' %}"/>
        <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
{% endblock %}


{% block body %}

    <body>
    <div id="construction">
        <p id="text">UNDER CONSTRUCTION</p>
    </div>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    {% load staticfiles %}
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id"
          content="642931691711-njc9uv4lt3lhnnqeh6bq26crdacqpt29.apps.googleusercontent.com">
    <link rel="stylesheet" type="text/css" href="{% static 'tag/css/login.css' %}"/>
    <script src="https://apis.google.com/js/platform.js" async defer></script>

</head>
<body >
<div id="signInButton" >
    <div   class="g-signin2 " data-onsuccess="onSignIn"></div>
</div>
<script>
    function onSignIn(googleUser) {
        // Useful data for your client-side scripts:
        {#        var profile = googleUser.getBasicProfile();#}
        {#        console.log("ID: " + profile.getId()); // Don't send this directly to your server!#}
        {#        console.log('Full Name: ' + profile.getName());#}
        {#        console.log('Given Name: ' + profile.getGivenName());#}
        {#        console.log('Family Name: ' + profile.getFamilyName());#}
        {#        console.log("Image URL: " + profile.getImageUrl());#}
        {#        console.log("Email: " + profile.getEmail());#}
        {##}
        {##}
        var idToken = googleUser.getAuthResponse().id_token;
        window.location = "{% url 'tag:log_in'  %}" + "?token=" + idToken;
        {#        console.log("ID Token: " + id_token);#}
        {#        var xhr = new XMLHttpRequest();#}
        {#        xhr.open('POST', 'http://localhost:8000/' + id_token +'/');#}

        {#        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');#}
        {#        xhr.onload = function () {#}
        {#            console.log('Signed in as: ' + xhr.responseText);#}
        {##}
        {##}
        {#        };#}
        {#        xhr.send('idtoken=' + id_token);#}

    }
</script>


</body>
</html>

templates/seenTags.html
{% extends 'index.html' %}

{% block title %}
    Seen Tags
{% endblock %}

{% block header %}
    Seen
{% endblock %}

{% block script %}

    <meta charset="UTF-8" name="google-signin-client_id"
          content="642931691711-njc9uv4lt3lhnnqeh6bq26crdacqpt29.apps.googleusercontent.com">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'tag/css/seenTags.css' %}"/>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
    {#    <script src="{% static 'tag/js/seenTags.js' %}"> </script>#}
{% endblock %}


{% block body %}

    <div id="parent">
        <div id="seenTags_table">

            <ul class="collapsible expandable ">

                <li>

                    <div id="co_header" class="collapsible-header ">

                        <div id="first"><p><strong>Seen Tag</strong></p></div>
                        <div id="second"><p><strong>Generated Address</strong></p></div>
                        <div id="third"><p><strong>Time</strong></p></div>


                    </div>


                    {#                  <div style="background: oldlace;width: 0px" class="collapsible-body"><span></span></div>#}
                </li>
                {% for info in client_info %}
                    <li>
                        <div id="co_header" class="collapsible-header ">
                            <div id="first"><p>{{ info.user_info.user_tag }}</p></div>
                            <div id="second"><p>
                                {{ BASE_TAG_URL }}{{ info.user_info.generated_tag }}</p>
                            </div>
                            <div id="third"><p>{{ info.client_time }}</p></div>


                        </div>
                        <div id="co_body" class="collapsible-body">
                            <div id="clientInfo">
                                <table>
                                    <tbody>
                                    <tr>
                                        <td><span id="constants">IP address </span></td>
                                        <td>{{ info.client_meta.HTTP_X_FORWARDED_FOR }}</td>

                                    </tr>
                                    <tr>
                                        <td><span id="constants">Server name </span></td>
                                        <td>{{ info.client_meta.SERVER_NAME }}</td>

                                    </tr>
                                    <tr>
                                        <td><span id="constants">Log name</span></td>
                                        <td>{{ info.client_meta.LOGNAME }}</td>

                                    </tr>
                                    <tr>
                                        <td><span id="constants">User </span></td>
                                        <td>{{ info.client_meta.USER }}</td>

                                    </tr>
                                    <tr>
                                        <td><span id="constants">User Agent </span></td>
                                        <td>{{ info.client_agent }}</td>

                                    </tr>
                                    <tr>
                                        <td><span id="constants">Times seen</span></td>
                                        <td>{{ info.times_seen }}</td>

                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </li>
                {% endfor %}

            </ul>
        </div>
    </div>

{% endblock %}

templates/tag.html
{% extends 'index.html' %}

{% block title %}
    Generator
{% endblock %}
{% block header %}
    Tracker
{% endblock %}

{% block script %}
    <meta charset="UTF-8">

    {% load staticfiles %}

    <meta name="google-signin-client_id"
          content="642931691711-njc9uv4lt3lhnnqeh6bq26crdacqpt29.apps.googleusercontent.com">

    <link rel="stylesheet" type="text/css" href="{% static 'tag/css/tag.css' %}"/>
    <script src="{% static 'tag/js/tag.js' %}"></script>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

{% endblock %}


{% block body %}
    <div id="generateForm">

        <form class="col s6" action="{% url 'tag:form' %}" method="get">
            <div id="box" class="row">
                <div class="input-field col s3 ">
                    <input id="id_tagname" maxlength="50" name="tagname" type="text"
                           {% if prev_tag is not None %}value="{{ prev_tag }}"{% endif %} required>

                    <label for="id_tagname">Enter tag</label>

                </div>
                <div id="submit_btn">
                    <button
                            class="waves-effect waves-light btn blue darken-4" type="submit"
                            onclick="return empty()">Generate
                    </button>
                </div>

            </div>


        </form>


    </div>

    <div id="generatedText">


        <input id="link" style="font-size: 12px" class="input-field" readonly="readonly" value="{{ generated_tag }}">
        <div id="copyButton">

            <a><img src="{% static 'tag/images/content_copy_black_36px.svg' %}"
                    onclick="copyText();M.toast({html: 'Text copied'});"/></a>


        </div>

    </div>


{% endblock %}

templates/unsued.html
{% extends 'index.html' %}

{% block title %}
    Unsued Tags
{% endblock %}
{% block header %}
    unsued
{% endblock %}

{% block body %}
    <!DOCTYPE html>
    <html lang="en">
    <head>

        {% load staticfiles %}
        <meta charset="UTF-8" name="google-signin-client_id"
              content="642931691711-njc9uv4lt3lhnnqeh6bq26crdacqpt29.apps.googleusercontent.com">
        <link rel="stylesheet" type="text/css" href="{% static 'tag/css/unsued.css' %}"/>
        <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

        {#    <script src="{% static 'tag/js/allTags.js' %}"> </script>#}

    </head>
    <body>
    <div id="parent">
        <div id="unsuedTags_table">
            <table class="highlight">
                <thead>
                <tr>
                    <!-- class "mdl-data-table__cell--non-numeric", align values to left -->
                    <th>Tag</th>
                    <th>Generated Address</th>
                    <th>Time</th>
                </tr>
                </thead>
                <tbody>

                <!-- Row 1 -->
                {% for info in user_info %}
                    <tr>
                        <!-- class "mdl-data-table__cell--non-numeric", align values to left -->
                        <td>{{ info.user_tag }}</td>
                        <td>{{ BASE_TAG_URL }}{{ info.generated_tag }}</td>
                        <td>{{ info.user_time }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
    </body>
    </html>
{% endblock %}